name: Build and Publish Docker Image

on:
    push:
      branches:
        - main
    workflow_dispatch:

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        run: |
          NAMESPACE=$(echo ${{ github.repository }} | awk '{print tolower($0)}')
          docker build . --tag ghcr.io/$NAMESPACE:latest
          docker push ghcr.io/$NAMESPACE:latest