name: Build and Publish Docker Image

on:
    push:
      branches:
        - main
    workflow_dispatch:

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Convert repository name to lowercase
        id: repo
        run: echo "::set-output name=repo::$(echo ${{ github.repository }} | awk '{print tolower($0)}')"

      - name: Build, tag, and push Docker image
        run: |
          docker build . --tag ghcr.io/${{ steps.repo.outputs.repo}}:latest
          docker push ghcr.io/${{ steps.repo.outputs.repo }}:latest