name: Build and Publish Docker Image

on:
    push:
      branches:
        - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1 
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.TOKEN_GITHUB }}

        - name: Convert repository name to lowercase
          id: repo
          run: echo "::set-output name=repo::$(echo ${{ github.repository }} | awk '{print tolower($0)}')"

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: ghcr.io/${{ steps.repo.outputs.repo }}:latest

        - name: Install gh cli
          run: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
            sudo apt-add-repository https://cli.github.com/packages
            sudo apt update
            sudo apt install gh

        - name: Upload Docker image as release asset
          env:
            GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          run: |
            IMAGE_ID=ghcr.io/${{ steps.repo.outputs.repo }}
            IMAGE_TAG=$(echo ${{ github.ref }} | sed 's/.*\///')
            docker tag $IMAGE_ID:latest $IMAGE_ID:$IMAGE_TAG
            docker save $IMAGE_ID:$IMAGE_TAG -o image.tar
            gh release upload $IMAGE_TAG image.tar --clobber